### ISSUE TITLE
The system can support importing SCORM files up to 100MB

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/moodle#2]
Here's some example files you can use:

https://www.dropbox.com/s/aj50c599jd2ht97/Involved%20Parties.zip?dl=0

https://www.dropbox.com/s/i1xg56o3h1cgvm5/Reclaimed%20Wood.zip?dl=0

**Comment by erazorbg** [comment]
Updated the PHP upload file limits to allow for 100Mb file uploads. 

I would like to push the branch I'm using here, but I don't have write access to this repository.

**Comment by Pcushing** [comment]
I just updated the rights so you should have the ability to edit this repo, manage issues, etc. Once you confirm you can push to the repo, feel free to close this out. 

Also, I was able to successfully import and play the SCORM package! 
https://nfcap-lms.herokuapp.com/mod/scorm/view.php?id=6

Question - What's the maximum we can bump the file upload size up to?

**Comment by erazorbg** [comment]
c347da3545f78c55270df75e1ab8ca42cd4364f1 adds a file to increase the limit for file uploads.

The maximum we can bump it will be limited to how much data Heroku instance can hold. If I remember correctly there is a 500mb for the dyno size. I think we can safely bump it to 200mb but you may run into issues when uploading multiple large files and exhaust the space available in the dyno. There is an option to delete files from the local system once uploaded to AWS that we can turn on to prevent this for happening.

**Comment by Pcushing** [comment]
OK. Good to know. I'll see if I can find out what the max SCORM package size is we might expect
