### ISSUE TITLE
Create script to GET the moodle cron url and get it running on Heroku scheduler 

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/moodle#4]

**Comment by erazorbg** [comment]
This is the URL that needs to be hit for the cronjob:
https://nfcap-lms.herokuapp.com/admin/cron.php

**Comment by Pcushing** [comment]
Do we literally just need to hit that URL with a basic GET request?  Can we just make a custom PHP or even bash script whose sole function is making that single GET request? If it's something we can call from a local terminal, we can do it on heroku's scheduler.

In rails, we'd write a rake task for this. I'm not sure what's standard for moodle / php.

**Comment by erazorbg** [comment]
Yes, this is what is needed just hit that url. There is an option to also add a passwod to the GET request but that's it just hit this URL anyway you like to. Bash, php, ruby whatever works best in this case.

**Comment by Pcushing** [comment]
Great. Can you create the script (I dont care what you write it in -- seems like it's only a few lines, tops) to make a GET request of that url, add it to the project, and add it to scheduler to run every ~10 minutes? 

I'm updating the name of this ticket to match.

**Comment by erazorbg** [comment]
Created a job to run in the scheduler every 10 minutes. Everything appears to work as expected.
